name: Build and Run OpenAiCodeReview By Main Maven Jar

on:
  push:
    branches:
      - github-master
  pull_request:
    branches:
      - github-master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '2'

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Code Review
        run: java -jar ./open-ai-code-review-sdk/target/open-ai-code-review-sdk-1.0.jar
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          AIHUBMIX_API_KEY: ${{ secrets.AIHUBMIX_API_KEY }}